### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by QingYeTenio** [EVE-China/blueprint-assistant-web#3]
能否把后端换成.net core。这样后端可以直接编译出独立部署的exe执行文件，然后使用Nginx进行代理，更加方便进行部署

**Comment by fantasy0v0** [comment]
谢谢你的建议，但是我本身是java开发，对.net core并不了解。

关于单独部署，因为这些最终都是放在服务器上的，所以在服务器上安装一个java对我来说是可以接受的，而且java的启动也是比较简单的，下面是我在服务器上的启动命令。
```java
java -jar /home/eve-blueprint/server/blueprint-service-1.0.0-SNAPSHOT-fat.jar -conf /home/eve-blueprint/server/conf/config.json
```
这个项目目前就是使用的nginx，只不过前端项目使用了服务端渲染(SSR)中转了一下。
