### ISSUE TITLE
一点建议（我不是甲方别打我）

### ISSUE THREAD

**Issue by yuhjnmwe** [EVE-China/blueprint-assistant-web#4]
现有的页面设计把材料列表制作的非常小
建议：按照EVE游戏内的设计把产出和费用计算放在最上面，而把材料列表放在最下面并考虑其他的展示方案

> 列如：产出-费用计算-详细材料

对于材料列表的展示方法我暂时没有更好的意见。

**fly safe o7**

**Comment by fantasy0v0** [comment]
好的，谢谢你的建议。

**Comment by fantasy0v0** [comment]
发现一款国外的同类产品, 可以用于参考它的界面设计。
http://www.eve-cost.eu/calculator
